/**
 * This file is auto-generated by scripts/generateSchema.ts
 * Do not edit manually
 */
import { components } from '@/api/schema'

/** Runtime representation of OpenAPI Schemas */
export const schemas = {
  Camera: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    name: {
      type: 'string',
      description: '摄像头名称',
    },
    basePath: {
      type: 'string',
      description: '基础路径',
    },
    segmentTemplate: {
      type: 'string | undefined',
      description: 'Segment解析模板',
    },
    enableDetection: {
      type: 'boolean | undefined',
      description: '启用目标检测',
    },
    detectionInterval: {
      type: 'string | number | undefined',
      description: '目标检测间隔(s)',
      format: 'int32',
    },
    detectionConfidence: {
      type: 'string | number | undefined',
      description: '目标检测最低置信度',
      format: 'double',
    },
  },
  CustomConditionalType: {
    toString: {
      type: '(radix?: number | undefined) => string',
    },
    toFixed: {
      type: '(fractionDigits?: number | undefined) => string',
    },
    toExponential: {
      type: '(fractionDigits?: number | undefined) => string',
    },
    toPrecision: {
      type: '(precision?: number | undefined) => string',
    },
    valueOf: {
      type: '() => number',
    },
    toLocaleString: {
      type: '{ (locales?: string | string[] | undefined, options?: Intl.NumberFormatOptions | undefined): string; (locales?: Intl.LocalesArgument, options?: Intl.NumberFormatOptions | undefined): string; }',
    },
  },
  CustomOrderByType: {
    toString: {
      type: '(radix?: number | undefined) => string',
    },
    toFixed: {
      type: '(fractionDigits?: number | undefined) => string',
    },
    toExponential: {
      type: '(fractionDigits?: number | undefined) => string',
    },
    toPrecision: {
      type: '(precision?: number | undefined) => string',
    },
    valueOf: {
      type: '() => number',
    },
    toLocaleString: {
      type: '{ (locales?: string | string[] | undefined, options?: Intl.NumberFormatOptions | undefined): string; (locales?: Intl.LocalesArgument, options?: Intl.NumberFormatOptions | undefined): string; }',
    },
  },
  FrameDetection: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    cameraId: {
      type: 'string | number | undefined',
      description: '摄像头ID',
      format: 'int64',
    },
    segmentId: {
      type: 'string | number | undefined',
      description: '视频片段ID',
      format: 'int64',
    },
    framePath: {
      type: 'string | undefined',
      description: '帧路径',
    },
    frameTime: {
      type: 'string | undefined',
      description: '帧时间',
      format: 'date-time',
    },
    targetId: {
      type: 'string | number | undefined',
      description: '目标ID',
      format: 'int32',
    },
    targetName: {
      type: 'string | undefined',
      description: '目标名称',
    },
    targetConfidence: {
      type: 'string | number | undefined',
      description: '目标置信度',
      format: 'double',
    },
    targetLocationX: {
      type: 'string | number | undefined',
      description: '目标坐标X',
      format: 'int32',
    },
    targetLocationY: {
      type: 'string | number | undefined',
      description: '目标坐标Y',
      format: 'int32',
    },
    targetSizeWidth: {
      type: 'string | number | undefined',
      description: '目标宽度',
      format: 'int32',
    },
    targetSizeHeight: {
      type: 'string | number | undefined',
      description: '目标高度',
      format: 'int32',
    },
  },
  IFormFile: {
    toString: {
      type: '() => string',
    },
    charAt: {
      type: '(pos: number) => string',
    },
    charCodeAt: {
      type: '(index: number) => number',
    },
    concat: {
      type: '(...strings: string[]) => string',
    },
    indexOf: {
      type: '(searchString: string, position?: number | undefined) => number',
    },
    lastIndexOf: {
      type: '(searchString: string, position?: number | undefined) => number',
    },
    localeCompare: {
      type: '{ (that: string): number; (that: string, locales?: string | string[] | undefined, options?: Intl.CollatorOptions | undefined): number; (that: string, locales?: Intl.LocalesArgument, options?: Intl.CollatorOptions | undefined): number; }',
    },
    match: {
      type: '{ (regexp: string | RegExp): RegExpMatchArray | null; (matcher: { [Symbol.match](string: string): RegExpMatchArray | null; }): RegExpMatchArray | null; }',
    },
    replace: {
      type: '{ (searchValue: string | RegExp, replaceValue: string): string; (searchValue: string | RegExp, replacer: (substring: string, ...args: any[]) => string): string; (searchValue: { [Symbol.replace](string: string, replaceValue: string): string; }, replaceValue: string): string; (searchValue: { [Symbol.replace](string: string, replacer: (substring: string, ...args: any[]) => string): string; }, replacer: (substring: string, ...args: any[]) => string): string; }',
    },
    search: {
      type: '{ (regexp: string | RegExp): number; (searcher: { [Symbol.search](string: string): number; }): number; }',
    },
    slice: {
      type: '(start?: number | undefined, end?: number | undefined) => string',
    },
    split: {
      type: '{ (separator: string | RegExp, limit?: number | undefined): string[]; (splitter: { [Symbol.split](string: string, limit?: number | undefined): string[]; }, limit?: number | undefined): string[]; }',
    },
    substring: {
      type: '(start: number, end?: number | undefined) => string',
    },
    toLowerCase: {
      type: '() => string',
    },
    toLocaleLowerCase: {
      type: '{ (locales?: string | string[] | undefined): string; (locales?: Intl.LocalesArgument): string; }',
    },
    toUpperCase: {
      type: '() => string',
    },
    toLocaleUpperCase: {
      type: '{ (locales?: string | string[] | undefined): string; (locales?: Intl.LocalesArgument): string; }',
    },
    trim: {
      type: '() => string',
    },
    length: {
      type: 'number',
    },
    substr: {
      type: '(from: number, length?: number | undefined) => string',
    },
    valueOf: {
      type: '() => string',
    },
    codePointAt: {
      type: '(pos: number) => number | undefined',
    },
    includes: {
      type: '(searchString: string, position?: number | undefined) => boolean',
    },
    endsWith: {
      type: '(searchString: string, endPosition?: number | undefined) => boolean',
    },
    normalize: {
      type: '{ (form: "NFC" | "NFD" | "NFKC" | "NFKD"): string; (form?: string | undefined): string; }',
    },
    repeat: {
      type: '(count: number) => string',
    },
    startsWith: {
      type: '(searchString: string, position?: number | undefined) => boolean',
    },
    anchor: {
      type: '(name: string) => string',
    },
    big: {
      type: '() => string',
    },
    blink: {
      type: '() => string',
    },
    bold: {
      type: '() => string',
    },
    fixed: {
      type: '() => string',
    },
    fontcolor: {
      type: '(color: string) => string',
    },
    fontsize: {
      type: '{ (size: number): string; (size: string): string; }',
    },
    italics: {
      type: '() => string',
    },
    link: {
      type: '(url: string) => string',
    },
    small: {
      type: '() => string',
    },
    strike: {
      type: '() => string',
    },
    sub: {
      type: '() => string',
    },
    sup: {
      type: '() => string',
    },
    padStart: {
      type: '(maxLength: number, fillString?: string | undefined) => string',
    },
    padEnd: {
      type: '(maxLength: number, fillString?: string | undefined) => string',
    },
    trimEnd: {
      type: '() => string',
    },
    trimStart: {
      type: '() => string',
    },
    trimLeft: {
      type: '() => string',
    },
    trimRight: {
      type: '() => string',
    },
    matchAll: {
      type: '(regexp: RegExp) => RegExpStringIterator<RegExpExecArray>',
    },
    replaceAll: {
      type: '{ (searchValue: string | RegExp, replaceValue: string): string; (searchValue: string | RegExp, replacer: (substring: string, ...args: any[]) => string): string; }',
    },
    at: {
      type: '(index: number) => string | undefined',
    },
    isWellFormed: {
      type: '() => boolean',
    },
    toWellFormed: {
      type: '() => string',
    },
    '__@iterator@115': {
      type: '() => StringIterator<string>',
    },
  },
  PagedResultOfCamera: {
    items: {
      type: '{ id?: string | number | undefined; name: string; basePath: string; segmentTemplate?: string | undefined; enableDetection?: boolean | undefined; detectionInterval?: string | number | undefined; detectionConfidence?: string | number | undefined; }[]',
      description: '当前页的数据列表',
    },
    totalCount: {
      type: 'string | number',
      description: '数据总条数',
      format: 'int32',
    },
    pageNumber: {
      type: 'string | number',
      description: '当前页码',
      format: 'int32',
    },
    pageSize: {
      type: 'string | number',
      description: '每页大小',
      format: 'int32',
    },
    totalPages: {
      type: 'string | number | undefined',
      description: '总页数',
      format: 'int32',
    },
    hasPreviousPage: {
      type: 'boolean | undefined',
      description: '是否有上一页',
    },
    hasNextPage: {
      type: 'boolean | undefined',
      description: '是否有下一页',
    },
  },
  PagedResultOfFrameDetection: {
    items: {
      type: '{ id?: string | number | undefined; cameraId?: string | number | undefined; segmentId?: string | number | undefined; framePath?: string | undefined; frameTime?: string | undefined; targetId?: string | number | undefined; targetName?: string | undefined; targetConfidence?: string | number | undefined; targetLocationX?: string | number | undefined; targetLocationY?: string | number | undefined; targetSizeWidth?: string | number | undefined; targetSizeHeight?: string | number | undefined; }[]',
      description: '当前页的数据列表',
    },
    totalCount: {
      type: 'string | number',
      description: '数据总条数',
      format: 'int32',
    },
    pageNumber: {
      type: 'string | number',
      description: '当前页码',
      format: 'int32',
    },
    pageSize: {
      type: 'string | number',
      description: '每页大小',
      format: 'int32',
    },
    totalPages: {
      type: 'string | number | undefined',
      description: '总页数',
      format: 'int32',
    },
    hasPreviousPage: {
      type: 'boolean | undefined',
      description: '是否有上一页',
    },
    hasNextPage: {
      type: 'boolean | undefined',
      description: '是否有下一页',
    },
  },
  PagedResultOfVideoSegment: {
    items: {
      type: '{ id?: string | number | undefined; cameraId?: string | number | undefined; syncTime?: string | undefined; path?: string | undefined; size?: string | number | undefined; startTime?: string | undefined; endTime?: string | undefined; durationActual?: string | undefined; durationTheoretical?: string | undefined; videoCodec?: string | undefined; videoWidth?: string | number | undefined; videoHeight?: string | number | undefined; videoFps?: string | number | undefined; videoBitrate?: string | number | undefined; audioCodec?: string | undefined; audioSampleRate?: string | number | undefined; audioChannels?: string | number | undefined; audioBitrate?: string | number | undefined; }[]',
      description: '当前页的数据列表',
    },
    totalCount: {
      type: 'string | number',
      description: '数据总条数',
      format: 'int32',
    },
    pageNumber: {
      type: 'string | number',
      description: '当前页码',
      format: 'int32',
    },
    pageSize: {
      type: 'string | number',
      description: '每页大小',
      format: 'int32',
    },
    totalPages: {
      type: 'string | number | undefined',
      description: '总页数',
      format: 'int32',
    },
    hasPreviousPage: {
      type: 'boolean | undefined',
      description: '是否有上一页',
    },
    hasNextPage: {
      type: 'boolean | undefined',
      description: '是否有下一页',
    },
  },
  QueryCondition: {
    fieldName: {
      type: 'string | undefined',
      description: '字段名',
    },
    fieldValue: {
      type: 'string | undefined',
      description: '字段值',
    },
    conditionalType: {
      type: 'number | undefined',
      description: '条件类型',
    },
    cSharpTypeName: {
      type: 'string | undefined',
      description: 'CSharp类型名',
    },
  },
  QueryDto: {
    pageNumber: {
      type: 'string | number | undefined',
      description: '页数',
      format: 'int32',
    },
    pageSize: {
      type: 'string | number | undefined',
      description: '每页大小',
      format: 'int32',
    },
    condition: {
      type: '{ fieldName?: string | undefined; fieldValue?: string | undefined; conditionalType?: number | undefined; cSharpTypeName?: string | undefined; }[] | null | undefined',
      description: '查询条件',
    },
    order: {
      type: '{ fieldName?: string | undefined; orderByType?: number | undefined; }[] | null | undefined',
      description: '排序条件',
    },
  },
  QueryOrder: {
    fieldName: {
      type: 'string | undefined',
      description: '字段名',
    },
    orderByType: {
      type: 'number | undefined',
      description: '排序类型',
    },
  },
  SystemController: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    controller: {
      type: 'string | undefined',
      description: '控制器',
    },
    title: {
      type: 'string | undefined',
      description: '标题',
    },
  },
  SystemRole: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    name: {
      type: 'string | undefined',
      description: '角色名',
    },
  },
  SystemUser: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    email: {
      type: 'string | undefined',
      description: '邮箱',
    },
    nickName: {
      type: 'string | undefined',
      description: '昵称',
    },
    password: {
      type: 'string | undefined',
      description: '密码',
    },
    role: {
      type: '(string | number)[] | undefined',
      description: '角色',
    },
  },
  Timeline: {
    time: {
      type: 'string',
      description: '时间点',
      format: 'date-time',
    },
    title: {
      type: 'string',
      description: '标题',
    },
    description: {
      type: 'string',
      description: '描述',
    },
    level: {
      type: 'string',
      description: '级别',
    },
  },
  UserVerifyType: {
    toString: {
      type: '(radix?: number | undefined) => string',
    },
    toFixed: {
      type: '(fractionDigits?: number | undefined) => string',
    },
    toExponential: {
      type: '(fractionDigits?: number | undefined) => string',
    },
    toPrecision: {
      type: '(precision?: number | undefined) => string',
    },
    valueOf: {
      type: '() => number',
    },
    toLocaleString: {
      type: '{ (locales?: string | string[] | undefined, options?: Intl.NumberFormatOptions | undefined): string; (locales?: Intl.LocalesArgument, options?: Intl.NumberFormatOptions | undefined): string; }',
    },
  },
  VideoSegment: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    cameraId: {
      type: 'string | number | undefined',
      description: '摄像头ID',
      format: 'int64',
    },
    syncTime: {
      type: 'string | undefined',
      description: '同步时间',
      format: 'date-time',
    },
    path: {
      type: 'string | undefined',
      description: '文件路径',
    },
    size: {
      type: 'string | number | undefined',
      description: '文件大小(MB)',
      format: 'double',
    },
    startTime: {
      type: 'string | undefined',
      description: '录制开始时间',
      format: 'date-time',
    },
    endTime: {
      type: 'string | undefined',
      description: '录制结束时间',
      format: 'date-time',
    },
    durationActual: {
      type: 'string | undefined',
      description: '实际录制时长',
    },
    durationTheoretical: {
      type: 'string | undefined',
      description: '理论录制时长',
    },
    videoCodec: {
      type: 'string | undefined',
      description: '视频编码器',
    },
    videoWidth: {
      type: 'string | number | undefined',
      description: '视频宽度',
      format: 'int32',
    },
    videoHeight: {
      type: 'string | number | undefined',
      description: '视频高度',
      format: 'int32',
    },
    videoFps: {
      type: 'string | number | undefined',
      description: '视频帧率(fps)',
      format: 'double',
    },
    videoBitrate: {
      type: 'string | number | undefined',
      description: '视频比特率(Kbps)',
      format: 'double',
    },
    audioCodec: {
      type: 'string | undefined',
      description: '音频编码器',
    },
    audioSampleRate: {
      type: 'string | number | undefined',
      description: '音频采样率(Hz)',
      format: 'double',
    },
    audioChannels: {
      type: 'string | number | undefined',
      description: '音频声道数',
      format: 'int32',
    },
    audioBitrate: {
      type: 'string | number | undefined',
      description: '音频比特率(Kbps)',
      format: 'double',
    },
  },
}

export type Camera = components['schemas']['Camera']
export type CustomConditionalType =
  components['schemas']['CustomConditionalType']
export type CustomOrderByType = components['schemas']['CustomOrderByType']
export type FrameDetection = components['schemas']['FrameDetection']
export type IFormFile = components['schemas']['IFormFile']
export type PagedResultOfCamera = components['schemas']['PagedResultOfCamera']
export type PagedResultOfFrameDetection =
  components['schemas']['PagedResultOfFrameDetection']
export type PagedResultOfVideoSegment =
  components['schemas']['PagedResultOfVideoSegment']
export type QueryCondition = components['schemas']['QueryCondition']
export type QueryDto = components['schemas']['QueryDto']
export type QueryOrder = components['schemas']['QueryOrder']
export type SystemController = components['schemas']['SystemController']
export type SystemRole = components['schemas']['SystemRole']
export type SystemUser = components['schemas']['SystemUser']
export type Timeline = components['schemas']['Timeline']
export type UserVerifyType = components['schemas']['UserVerifyType']
export type VideoSegment = components['schemas']['VideoSegment']
