/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Authentication/SendVerifyCode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发送验证码 */
        post: {
            parameters: {
                query?: {
                    /** @description 验证方式 */
                    verifyType?: components["schemas"]["UserVerifyType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/SetAvatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设置用户头像 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemRole"];
                    "text/json": components["schemas"]["SystemRole"];
                    "application/*+json": components["schemas"]["SystemRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户注册 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 注册信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddRoleGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向角色授权控制器 */
        post: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number | string;
                    /** @description 控制器ID */
                    controllerId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddUserGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向用户授权控制器 */
        post: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number | string;
                    /** @description 控制器ID */
                    controllerId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除角色 */
        delete: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户 */
        delete: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteRoleGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除角色授权 */
        delete: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number | string;
                    /** @description 控制器ID */
                    controllerId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteUserGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户授权 */
        delete: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number | string;
                    /** @description 控制器ID */
                    controllerId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/ModifyRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改角色 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemRole"];
                    "text/json": components["schemas"]["SystemRole"];
                    "application/*+json": components["schemas"]["SystemRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/ModifyUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改用户 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 用户信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/GetKey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取RSA公钥 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有用户列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemUser"][];
                        "application/json": components["schemas"]["SystemUser"][];
                        "text/json": components["schemas"]["SystemUser"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有角色列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemRole"][];
                        "application/json": components["schemas"]["SystemRole"][];
                        "text/json": components["schemas"]["SystemRole"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/UserControllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户控制器列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: string;
                    /** @description 是否授权 */
                    isGranted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/RoleControllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取角色控制器列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: string;
                    /** @description 是否授权 */
                    isGranted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/CurrentUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemUser"];
                        "application/json": components["schemas"]["SystemUser"];
                        "text/json": components["schemas"]["SystemUser"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/GetAvatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户头像 */
        get: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    id?: string;
                    /** @description token */
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Granted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取已授权的控制器 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/RefreshToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 刷新token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcLoginAddress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取OIDC登录地址 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC登录 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcCallback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC回调处理 */
        get: {
            parameters: {
                query?: {
                    /** @description 回调中的授权码 */
                    code?: string;
                    /** @description 回调中的状态参数 */
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/SyncAndCache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 同步索引并重建缓存 */
        post: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/GetTimeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取时间轴 */
        get: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Timeline"][];
                        "application/json": components["schemas"]["Timeline"][];
                        "text/json": components["schemas"]["Timeline"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/ClearDetections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 清除检测结果 */
        delete: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除数据 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例列表 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Camera"][];
                    "text/json": components["schemas"]["Camera"][];
                    "application/*+json": components["schemas"]["Camera"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加数据
         * @description 批量添加数据
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Camera"][];
                    "text/json": components["schemas"]["Camera"][];
                    "application/*+json": components["schemas"]["Camera"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": (number | string)[];
                        "application/json": (number | string)[];
                        "text/json": (number | string)[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新数据
         * @description 批量更新数据
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Camera"][];
                    "text/json": components["schemas"]["Camera"][];
                    "application/*+json": components["schemas"]["Camera"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询列表
         * @description 按照条件和排序方式查询数据列表
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfCamera"];
                        "application/json": components["schemas"]["PagedResultOfCamera"];
                        "text/json": components["schemas"]["PagedResultOfCamera"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 统计总数
         * @description 按照条件统计数据总数
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/DownloadExcel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下载Excel
         * @description 按照条件和排序方式将数据导出为Excel文件
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Detection/GetImage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取检测图片 */
        get: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                    /** @description 视频片段ID */
                    segmentId?: string;
                    /** @description 帧路径 */
                    framePath?: string;
                    /** @description token */
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Detection/Insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加数据
         * @description 批量添加数据
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FrameDetection"][];
                    "text/json": components["schemas"]["FrameDetection"][];
                    "application/*+json": components["schemas"]["FrameDetection"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": (number | string)[];
                        "application/json": (number | string)[];
                        "text/json": (number | string)[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Detection/Delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除数据
         * @description 批量删除数据
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FrameDetection"][];
                    "text/json": components["schemas"]["FrameDetection"][];
                    "application/*+json": components["schemas"]["FrameDetection"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Detection/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新数据
         * @description 批量更新数据
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FrameDetection"][];
                    "text/json": components["schemas"]["FrameDetection"][];
                    "application/*+json": components["schemas"]["FrameDetection"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Detection/Query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询列表
         * @description 按照条件和排序方式查询数据列表
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfFrameDetection"];
                        "application/json": components["schemas"]["PagedResultOfFrameDetection"];
                        "text/json": components["schemas"]["PagedResultOfFrameDetection"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Detection/Count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 统计总数
         * @description 按照条件统计数据总数
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Detection/DownloadExcel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下载Excel
         * @description 按照条件和排序方式将数据导出为Excel文件
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/GetThumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取缩略图 */
        get: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                    /** @description 视频片段ID */
                    segmentId?: string;
                    /** @description token */
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除数据 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例列表 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VideoSegment"][];
                    "text/json": components["schemas"]["VideoSegment"][];
                    "application/*+json": components["schemas"]["VideoSegment"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加数据
         * @description 批量添加数据
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VideoSegment"][];
                    "text/json": components["schemas"]["VideoSegment"][];
                    "application/*+json": components["schemas"]["VideoSegment"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": (number | string)[];
                        "application/json": (number | string)[];
                        "text/json": (number | string)[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新数据
         * @description 批量更新数据
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VideoSegment"][];
                    "text/json": components["schemas"]["VideoSegment"][];
                    "application/*+json": components["schemas"]["VideoSegment"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询列表
         * @description 按照条件和排序方式查询数据列表
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfVideoSegment"];
                        "application/json": components["schemas"]["PagedResultOfVideoSegment"];
                        "text/json": components["schemas"]["PagedResultOfVideoSegment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 统计总数
         * @description 按照条件统计数据总数
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/DownloadExcel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下载Excel
         * @description 按照条件和排序方式将数据导出为Excel文件
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Settings/GetStorageInfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取存储占用信息(MB) */
        get: {
            parameters: {
                query?: {
                    /** @description cache / detection */
                    path?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": {
                            [key: string]: number | string;
                        };
                        "application/json": {
                            [key: string]: number | string;
                        };
                        "text/json": {
                            [key: string]: number | string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Video/SegmentStream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定Segment的视频流(FLV) */
        get: {
            parameters: {
                query?: {
                    /** @description 视频片段ID */
                    segmentId?: string;
                    /** @description token */
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Video/CameraPlaylist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 摄像头播放列表(HLS) */
        get: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                    /** @description 开始时间 */
                    start?: number | string;
                    /** @description token */
                    token?: string;
                    /** @description 持续时间（秒） */
                    durationSec?: number | string;
                    /** @description 分片时长（秒） */
                    segmentSec?: number | string;
                    /** @description 会话ID（可选） */
                    sid?: string;
                    /** @description 是否使用源地址（可选） */
                    sourceAddress?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Video/CameraStream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 摄像头视频流(HLS) */
        get: {
            parameters: {
                query?: {
                    /** @description 会话ID */
                    sid?: string;
                    /** @description 视频片段序列号 */
                    seq?: number | string;
                    /** @description token */
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 摄像头 */
        Camera: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /** @description 摄像头名称 */
            name: string;
            /** @description 基础路径 */
            basePath: string;
            /** @description Segment解析模板 */
            segmentTemplate?: string;
            /** @description 启用目标检测 */
            enableDetection?: boolean;
            /**
             * Format: int32
             * @description 目标检测间隔(s)
             */
            detectionInterval?: number | string;
            /**
             * Format: double
             * @description 目标检测最低置信度
             */
            detectionConfidence?: number | string;
        };
        /**
         * @description 条件类型条件类型
         *
         *     | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | Equal |
         *     | 1 | Like |
         *     | 2 | GreaterThan |
         *     | 3 | GreaterThanOrEqual |
         *     | 4 | LessThan |
         *     | 5 | LessThanOrEqual |
         *     | 6 | In |
         *     | 7 | NotIn |
         *     | 8 | LikeLeft |
         *     | 9 | LikeRight |
         *     | 10 | NoEqual |
         *     | 11 | IsNullOrEmpty |
         *     | 12 | IsNotNullOrEmpty |
         *     | 13 | NoLike |
         *     | 14 | EqualNull |
         *     | 15 | InLike |
         *     | 16 | Range |
         */
        CustomConditionalType: number;
        /**
         * @description 排序类型排序类型
         *
         *     | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | Asc |
         *     | 1 | Desc |
         */
        CustomOrderByType: number;
        /** @description 帧目标检测 */
        FrameDetection: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /**
             * Format: int64
             * @description 摄像头ID
             */
            cameraId?: number | string;
            /**
             * Format: int64
             * @description 视频片段ID
             */
            segmentId?: number | string;
            /** @description 帧路径 */
            framePath?: string;
            /**
             * Format: date-time
             * @description 帧时间
             */
            frameTime?: string;
            /**
             * Format: int32
             * @description 目标ID
             */
            targetId?: number | string;
            /** @description 目标名称 */
            targetName?: string;
            /**
             * Format: double
             * @description 目标置信度
             */
            targetConfidence?: number | string;
            /**
             * Format: int32
             * @description 目标坐标X
             */
            targetLocationX?: number | string;
            /**
             * Format: int32
             * @description 目标坐标Y
             */
            targetLocationY?: number | string;
            /**
             * Format: int32
             * @description 目标宽度
             */
            targetSizeWidth?: number | string;
            /**
             * Format: int32
             * @description 目标高度
             */
            targetSizeHeight?: number | string;
        };
        /** Format: binary */
        IFormFile: string;
        /** @description 通用分页响应结果 */
        PagedResultOfCamera: {
            /** @description 当前页的数据列表 */
            items: components["schemas"]["Camera"][];
            /**
             * Format: int32
             * @description 数据总条数
             */
            totalCount: number | string;
            /**
             * Format: int32
             * @description 当前页码
             */
            pageNumber: number | string;
            /**
             * Format: int32
             * @description 每页大小
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description 总页数
             */
            totalPages?: number | string;
            /** @description 是否有上一页 */
            hasPreviousPage?: boolean;
            /** @description 是否有下一页 */
            hasNextPage?: boolean;
        };
        /** @description 通用分页响应结果 */
        PagedResultOfFrameDetection: {
            /** @description 当前页的数据列表 */
            items: components["schemas"]["FrameDetection"][];
            /**
             * Format: int32
             * @description 数据总条数
             */
            totalCount: number | string;
            /**
             * Format: int32
             * @description 当前页码
             */
            pageNumber: number | string;
            /**
             * Format: int32
             * @description 每页大小
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description 总页数
             */
            totalPages?: number | string;
            /** @description 是否有上一页 */
            hasPreviousPage?: boolean;
            /** @description 是否有下一页 */
            hasNextPage?: boolean;
        };
        /** @description 通用分页响应结果 */
        PagedResultOfVideoSegment: {
            /** @description 当前页的数据列表 */
            items: components["schemas"]["VideoSegment"][];
            /**
             * Format: int32
             * @description 数据总条数
             */
            totalCount: number | string;
            /**
             * Format: int32
             * @description 当前页码
             */
            pageNumber: number | string;
            /**
             * Format: int32
             * @description 每页大小
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description 总页数
             */
            totalPages?: number | string;
            /** @description 是否有上一页 */
            hasPreviousPage?: boolean;
            /** @description 是否有下一页 */
            hasNextPage?: boolean;
        };
        /** @description 查询条件 */
        QueryCondition: {
            /** @description 字段名 */
            fieldName?: string;
            /** @description 字段值 */
            fieldValue?: string;
            /** @description 条件类型 */
            conditionalType?: components["schemas"]["CustomConditionalType"];
            /** @description CSharp类型名 */
            cSharpTypeName?: string;
        };
        /** @description 查询参数 */
        QueryDto: {
            /**
             * Format: int32
             * @description 页数
             */
            pageNumber?: number | string;
            /**
             * Format: int32
             * @description 每页大小
             */
            pageSize?: number | string;
            /** @description 查询条件 */
            condition?: null | components["schemas"]["QueryCondition"][];
            /** @description 排序条件 */
            order?: null | components["schemas"]["QueryOrder"][];
        };
        /** @description 排序条件 */
        QueryOrder: {
            /** @description 字段名 */
            fieldName?: string;
            /** @description 排序类型 */
            orderByType?: components["schemas"]["CustomOrderByType"];
        };
        /** @description 系统控制器 */
        SystemController: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /** @description 控制器 */
            controller?: string;
            /** @description 标题 */
            title?: string;
        };
        /** @description 系统角色 */
        SystemRole: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /** @description 角色名 */
            name?: string;
        };
        /** @description 系统用户 */
        SystemUser: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /** @description 邮箱 */
            email?: string;
            /** @description 昵称 */
            nickName?: string;
            /** @description 密码 */
            password?: string;
            /** @description 角色 */
            role?: (number | string)[];
        };
        /** @description 时间轴 */
        Timeline: {
            /**
             * Format: date-time
             * @description 时间点
             */
            time: string;
            /** @description 标题 */
            title: string;
            /**
             * @description 描述
             * @default
             */
            description: string;
            /**
             * @description 级别
             * @default verbose
             */
            level: string;
        };
        /**
         * @description | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | 邮箱 |
         */
        UserVerifyType: number;
        /** @description 视频片段 */
        VideoSegment: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /**
             * Format: int64
             * @description 摄像头ID
             */
            cameraId?: number | string;
            /**
             * Format: date-time
             * @description 同步时间
             */
            syncTime?: string;
            /** @description 文件路径 */
            path?: string;
            /**
             * Format: double
             * @description 文件大小(MB)
             */
            size?: number | string;
            /**
             * Format: date-time
             * @description 录制开始时间
             */
            startTime?: string;
            /**
             * Format: date-time
             * @description 录制结束时间
             */
            endTime?: string;
            /** @description 实际录制时长 */
            durationActual?: string;
            /** @description 理论录制时长 */
            durationTheoretical?: string;
            /** @description 视频编码器 */
            videoCodec?: string;
            /**
             * Format: int32
             * @description 视频宽度
             */
            videoWidth?: number | string;
            /**
             * Format: int32
             * @description 视频高度
             */
            videoHeight?: number | string;
            /**
             * Format: double
             * @description 视频帧率(fps)
             */
            videoFps?: number | string;
            /**
             * Format: double
             * @description 视频比特率(Kbps)
             */
            videoBitrate?: number | string;
            /** @description 音频编码器 */
            audioCodec?: string;
            /**
             * Format: double
             * @description 音频采样率(Hz)
             */
            audioSampleRate?: number | string;
            /**
             * Format: int32
             * @description 音频声道数
             */
            audioChannels?: number | string;
            /**
             * Format: double
             * @description 音频比特率(Kbps)
             */
            audioBitrate?: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
