/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Authentication/SendVerifyCode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发送验证码 */
        post: {
            parameters: {
                query?: {
                    /** @description 验证方式 */
                    verifyType?: components["schemas"]["UserVerifyType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录信息 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录信息 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SystemRole"];
                    "text/json": components["schemas"]["SystemRole"];
                    "application/*+json": components["schemas"]["SystemRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户注册 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 注册信息 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddRoleGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向角色授权控制器 */
        post: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number;
                    /** @description 控制器ID */
                    controllerId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddUserGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向用户授权控制器 */
        post: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number;
                    /** @description 控制器ID */
                    controllerId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除角色 */
        delete: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户 */
        delete: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteRoleGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除角色授权 */
        delete: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number;
                    /** @description 控制器ID */
                    controllerId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteUserGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户授权 */
        delete: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number;
                    /** @description 控制器ID */
                    controllerId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/ModifyRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改角色 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SystemRole"];
                    "text/json": components["schemas"]["SystemRole"];
                    "application/*+json": components["schemas"]["SystemRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/ModifyUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改用户 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 用户信息 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/GetKey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取RSA公钥 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有用户列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemUser"][];
                        "application/json": components["schemas"]["SystemUser"][];
                        "text/json": components["schemas"]["SystemUser"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有角色列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemRole"][];
                        "application/json": components["schemas"]["SystemRole"][];
                        "text/json": components["schemas"]["SystemRole"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/UserControllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户控制器列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: string;
                    /** @description 是否授权 */
                    isGranted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/RoleControllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取角色控制器列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: string;
                    /** @description 是否授权 */
                    isGranted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/CurrentUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemUser"];
                        "application/json": components["schemas"]["SystemUser"];
                        "text/json": components["schemas"]["SystemUser"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Granted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取已授权的控制器 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/RefreshToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 刷新token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcLoginAddress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取OIDC登录地址 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC登录 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcCallback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC回调处理 */
        get: {
            parameters: {
                query?: {
                    /** @description 回调中的授权码 */
                    code?: string;
                    /** @description 回调中的状态参数 */
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/SyncAndCache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 同步索引并重建缓存 */
        post: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/GetTimeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取时间轴 */
        get: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Timeline"][];
                        "application/json": components["schemas"]["Timeline"][];
                        "text/json": components["schemas"]["Timeline"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除数据 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例列表 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Camera"][];
                    "text/json": components["schemas"]["Camera"][];
                    "application/*+json": components["schemas"]["Camera"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加数据 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例列表 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Camera"][];
                    "text/json": components["schemas"]["Camera"][];
                    "application/*+json": components["schemas"]["Camera"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number[];
                        "application/json": number[];
                        "text/json": number[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新数据 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例列表 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Camera"][];
                    "text/json": components["schemas"]["Camera"][];
                    "application/*+json": components["schemas"]["Camera"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 查询列表 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Camera"][];
                        "application/json": components["schemas"]["Camera"][];
                        "text/json": components["schemas"]["Camera"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Camera/Count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 统计总数 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/GetThumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取缩略图 */
        get: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                    /** @description 视频片段ID */
                    segmentId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除数据 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例列表 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VideoSegment"][];
                    "text/json": components["schemas"]["VideoSegment"][];
                    "application/*+json": components["schemas"]["VideoSegment"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加数据 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例列表 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VideoSegment"][];
                    "text/json": components["schemas"]["VideoSegment"][];
                    "application/*+json": components["schemas"]["VideoSegment"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number[];
                        "application/json": number[];
                        "text/json": number[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新数据 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 实例列表 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VideoSegment"][];
                    "text/json": components["schemas"]["VideoSegment"][];
                    "application/*+json": components["schemas"]["VideoSegment"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 查询列表 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VideoSegment"][];
                        "application/json": components["schemas"]["VideoSegment"][];
                        "text/json": components["schemas"]["VideoSegment"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Segment/Count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 统计总数 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number;
                        "application/json": number;
                        "text/json": number;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Video/SegmentStream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指定Segment的视频流(FLV) */
        get: {
            parameters: {
                query?: {
                    /** @description 视频片段ID */
                    segmentId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Video/CameraPlaylist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 摄像头播放列表(HLS) */
        get: {
            parameters: {
                query?: {
                    /** @description 摄像头ID */
                    cameraId?: string;
                    /** @description 开始时间 */
                    start?: number;
                    /** @description 持续时间（秒） */
                    durationSec?: number;
                    /** @description 分片时长（秒） */
                    segmentSec?: number;
                    /** @description 会话ID（可选） */
                    sid?: string;
                    /** @description 是否使用源地址（可选） */
                    sourceAddress?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Video/CameraStream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 摄像头视频流(HLS) */
        get: {
            parameters: {
                query?: {
                    /** @description 会话ID */
                    sid?: string;
                    /** @description 视频片段序列号 */
                    seq?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 摄像头 */
        Camera: {
            /**
             * Format: int64
             * @description ID
             */
            Id?: number;
            /** @description 摄像头名称 */
            Name?: string | null;
            /** @description 基础路径 */
            BasePath?: string | null;
            /** @description Segment解析模板 */
            SegmentTemplate?: string | null;
        };
        /**
         * Format: int32
         * @description
         *
         *     | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | Equal |
         *     | 1 | Like |
         *     | 2 | GreaterThan |
         *     | 3 | GreaterThanOrEqual |
         *     | 4 | LessThan |
         *     | 5 | LessThanOrEqual |
         *     | 6 | In |
         *     | 7 | NotIn |
         *     | 8 | LikeLeft |
         *     | 9 | LikeRight |
         *     | 10 | NoEqual |
         *     | 11 | IsNullOrEmpty |
         *     | 12 | IsNotNullOrEmpty |
         *     | 13 | NoLike |
         *     | 14 | EqualNull |
         *     | 15 | InLike |
         *     | 16 | Range |
         *
         * @enum {integer}
         */
        CustomConditionalType: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16;
        /**
         * Format: int32
         * @description
         *
         *     | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | Asc |
         *     | 1 | Desc |
         *
         * @enum {integer}
         */
        CustomOrderByType: 0 | 1;
        QueryCondition: {
            /** @description 字段名 */
            FieldName?: string | null;
            /** @description 字段值 */
            FieldValue?: string | null;
            ConditionalType?: components["schemas"]["CustomConditionalType"];
            /** @description CSharp类型名 */
            CSharpTypeName?: string | null;
        };
        QueryDto: {
            /**
             * Format: int32
             * @description 页数
             */
            PageNumber?: number;
            /**
             * Format: int32
             * @description 每页大小
             */
            PageSize?: number;
            /** @description 查询条件 */
            Condition?: components["schemas"]["QueryCondition"][] | null;
            /** @description 排序条件 */
            Order?: components["schemas"]["QueryOrder"][] | null;
        };
        QueryOrder: {
            /** @description 字段名 */
            FieldName?: string | null;
            OrderByType?: components["schemas"]["CustomOrderByType"];
        };
        /** @description 系统控制器 */
        SystemController: {
            /**
             * Format: int64
             * @description ID
             */
            Id?: number;
            /** @description 控制器 */
            Controller?: string | null;
            /** @description 标题 */
            Title?: string | null;
        };
        /** @description 系统角色 */
        SystemRole: {
            /**
             * Format: int64
             * @description ID
             */
            Id?: number;
            /** @description 角色名 */
            Name?: string | null;
        };
        /** @description 系统用户 */
        SystemUser: {
            /**
             * Format: int64
             * @description ID
             */
            Id?: number;
            /** @description 邮箱 */
            Email?: string | null;
            /** @description 昵称 */
            NickName?: string | null;
            /** @description 密码 */
            Password?: string | null;
            /** @description 角色 */
            Role?: number[] | null;
        };
        /** @description 时间轴 */
        Timeline: {
            /**
             * Format: date-time
             * @description 时间点
             */
            Time?: string;
            /** @description 标题 */
            Title?: string | null;
            /** @description 描述 */
            Description?: string | null;
            /** @description 级别 */
            Level?: string | null;
        };
        /**
         * Format: int32
         * @description
         *
         *     | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | 邮箱 |
         *
         * @enum {integer}
         */
        UserVerifyType: 0;
        /** @description 视频片段 */
        VideoSegment: {
            /**
             * Format: int64
             * @description ID
             */
            Id?: number;
            /**
             * Format: int64
             * @description 摄像头ID
             */
            CameraId?: number;
            /**
             * Format: date-time
             * @description 同步时间
             */
            SyncTime?: string;
            /** @description 文件路径 */
            Path?: string | null;
            /**
             * Format: double
             * @description 文件大小(MB)
             */
            Size?: number;
            /**
             * Format: date-time
             * @description 录制开始时间
             */
            StartTime?: string;
            /**
             * Format: date-time
             * @description 录制结束时间
             */
            EndTime?: string;
            /**
             * Format: date-span
             * @description 实际录制时长
             */
            DurationActual?: string;
            /**
             * Format: date-span
             * @description 理论录制时长
             */
            DurationTheoretical?: string;
            /** @description 视频编码器 */
            VideoCodec?: string | null;
            /**
             * Format: int32
             * @description 视频宽度
             */
            VideoWidth?: number;
            /**
             * Format: int32
             * @description 视频高度
             */
            VideoHeight?: number;
            /**
             * Format: double
             * @description 视频帧率(fps)
             */
            VideoFps?: number;
            /**
             * Format: double
             * @description 视频比特率(Kbps)
             */
            VideoBitrate?: number;
            /** @description 音频编码器 */
            AudioCodec?: string | null;
            /**
             * Format: double
             * @description 音频采样率(Hz)
             */
            AudioSampleRate?: number;
            /**
             * Format: int32
             * @description 音频声道数
             */
            AudioChannels?: number;
            /**
             * Format: double
             * @description 音频比特率(Kbps)
             */
            AudioBitrate?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
