name: Docker Image CI
on:
  push:
    branches:
      - main # 推送到主分支时触发
    paths:
      - '**' # 监控所有文件变更
      - '!.github/**' # 排除 .github 目录的变更

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository # 签出代码
        uses: actions/checkout@v4

      - name: Set up QEMU # 启用 QEMU 支持
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx # 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry # 登录到 GitHub 容器注册表
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image # 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/time-capsule:latest
            ghcr.io/${{ github.repository_owner }}/time-capsule:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max